# Generated by Django 5.1.2 on 2024-10-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
