# Generated by Django 5.1.2 on 2024-10-28 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_rename_end_time_rental_ending_time_and_more'),
        ('managers', '0004_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='balance',
        ),
        migrations.AlterField(
            model_name='manager',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.location'),
        ),
    ]
